import Navbar from '@/components/navbar/Navbar';
import './globals.css';
import { Red_Hat_Text } from 'next/font/google';
import Footer from '@/components/footer/Footer';

const rh = Red_Hat_Text({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={rh.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
